name: Docker Build and Run Check

on:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image
        run: docker build -t career-board .

      - name: Run container and test
        run: |
          docker run -d -p 4200:80 --name career-board-container career-board
          sleep 5  # Give the container time to start
          docker ps | grep career-board-container  # Ensure container is running

      - name: Stop and remove container
        run: docker rm -f career-board-container
